name: Move Notebooks to Python Folder

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 🟢 Required to allow pushing changes

jobs:
  move-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 🟢 Use the default GitHub Actions token

    - name: Move .ipynb files to Python folder
      run: |
        mkdir -p Python
        shopt -s nullglob
        for file in *.ipynb; do
          git mv "$file" Python/
        done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Auto-moved notebooks to Python folder" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
